// This file was generated by lezer-generator. You probably shouldn't edit it.
export const
  Program = 1,
  KeywordControl = 2,
  SupportFunction = 3,
  KeywordOther = 4,
  EntityNameType = 5,
  ReasoningPhrase = 6,
  Comment = 7,
  OpenParen = 8,
  CloseParen = 9,
  OpenBrace = 10,
  CloseBrace = 11,
  OpenBracket = 12,
  CloseBracket = 13,
  DefinitionBlock = 14,
  Proof = 15,
  NowBlock = 16,
  HerebyBlock = 17
